server:
  port: 8081
  
spring:
  profiles:
    active: local   
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: hyojin
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver
     
  jpa:
    properties:
      hibernate: 
        show_sql: true
        format_sql: true

     
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace 